# Generated by Django 5.0.2 on 2025-04-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field', models.CharField(max_length=100)),
                ('source_field', models.CharField(max_length=100)),
                ('source_system', models.CharField(max_length=100)),
                ('transformation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=100)),
                ('source_field', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certified', models.BooleanField(default=False)),
                ('issues', models.TextField(blank=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usecase')),
            ],
        ),
    ]
